version: '2'
.catalog:
  name: "RStudio with Microarray Packages"
  version: "v0.9-jan2018"
  description: "RStudio session with Microarray tagged packages installed"
  questions:
    - variable: host
      label: "Host"
      description: "Chose a host to run container:"
      default: "axiohost17"
      require: true
      type: enum
      options:
        - "axiohost13"
        - "axiohost17"
  uuid: microarray-0
