RTGCore:
  ports:
  - 3000
  labels:
    io.rancher.container.pull_image: always
  hostname: axiohost13
  image: dnadave/rtg-core:may2016-test
  volumes:
  - /Projects/BIGdata:/data:rw
  net: bridge
  privileged: true
