RTGCore:
  ports:
  - 3000
  labels:
    io.rancher.container.pull_image: always
  hostname: ${host}
  image: dnadave/rtg-core:mar2017
  volumes:
  - /Projects/BIGdata:/data:rw
  net: bridge
  privileged: true
