version: '2'
services:
  RTGCore:
    ports:
      - 3000
    labels:
      io.rancher.container.pull_image: always
    hostname: ${host}
    image: dnadave/rtg-core:feb2018
    volumes:
      - /Projects/BIGdata:/data:rw
      - /Projects/data:/ssd:rw
#    net: bridge
    privileged: true
    labels:
      #make microarray a global service
      io.rancher.scheduler.global: 'true'
      # make microarray only run on host with specified value:
      io.rancher.scheduler.affinity:host_label: ServerID=${host}
