shinygwas:
  image: jjsaxio/axio_shinydemo:jan2017
  ports:
  - 80
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
#  net: bridge
  privileged: true
  labels:
    #make microarray a global service
    io.rancher.scheduler.global: 'true'
    # make microarray only run on host with specified value:
    io.rancher.scheduler.affinity:host_label: ServerID=${host}
